default_language_version:
    python: python3.8
repos:
  #  - repo: https://gitlab.com/PyCQA/flake8
  #    rev: 3.8.3
  #    hooks:
  #      - id: flake8
  - repo: https://github.com/psf/black
    rev: 21.12b0
    hooks:
      - id: black
  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: 'v0.770'
  #    hooks:
  #      - id: mypy
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
#  - repo: git@github.com:humitos/mirrors-autoflake.git
#    rev: v1.1
#    hooks:
#      - id: autoflake
#        args: [ '--in-place', '--remove-all-unused-imports' ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-docstring-first
      - id: debug-statements
      - id: flake8
      - id: trailing-whitespace
      - id: check-ast
      - id: check-builtin-literals
      - id: detect-private-key
      - id: mixed-line-ending
