[tool.poetry]
name = "tgintegration"
version = "0.4.0"
description = "An Integration Test Library for Telegram Messenger Bots on top of Pyrogram."
authors = ["Joscha GÃ¶tzer <joscha.goetzer@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "==3.*,>=3.6.7"
typing-extensions = "^3.7.4"
pyrogram = "^1.0.1"

[tool.poetry.dev-dependencies]
bumpversion = "==0.5.3"
wheel = "==0.29.0"
watchdog = "==0.8.3"
flake8 = "==2.6.0"
tox = "^3.14.5"
coverage = "==4.1"
PyYAML = "==5.1"
pytest = "^5.3.5"
pytest-runner = "^5.2"
sphinx = "==2.*,>=2.3.0"
sphinx-autodoc-typehints = "==1.*,>=1.10.3"
tgcrypto = "==1.*,>=1.2.0"
python-decouple = "^3.3"
pytest-asyncio = "^0.10.0"

[tool.dephell.main]
from = {format = "poetry", path = "pyproject.toml"}
to = {format = "setuppy", path = "setup.py"}
versioning = "semver"

[build-system]
requires = ["poetry>=1.0.5"]
build-backend = "poetry.masonry.api"
